# .github/workflows/publish.yml

name: Publish to npm

on:
  push:
    # Run this workflow on version tags
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Publish package
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish
